report_path: ./misc/notebooks/report.ipynb

nd2:
  iter_axs:
    - 'z'
    - 'm'
    - 't'
  bdl_axs:
    - 'y'
    - 'x'
  naming_axs:
  - 'm'

mpp: 0.31302569743655434

queue_size: 200

opt_flow_model: gma

gma:
  # restore checkpoint
  model: gma-sintel.pth
  # define model name
  model_name: GMA
  # number of heads in attention and aggregation
  num_heads: 1
  # only use position-wise attention
  position_only: no
  # use position and content-wise attention
  position_and_content: no
  # use mixed precision
  mixed_precision: no
  # cpu or cuda (for gpu)
  device: cpu
